selenium-hub:
  image: selenium/hub
  ports:
  - 4444:4444
  environment:
    - GRID_MAX_SESSION=10
    - TIMEOUT=1200000
    - GRID_TIMEOUT=0
    - GRID_NEW_SESSION_WAIT_TIMEOUT=-1

chrome-1:
  image: selenium/node-chrome:3.141
  links:
  - selenium-hub:hub
  volumes:
  - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
  environment:
    - NODE_MAX_SESSION=5
    - NODE_MAX_INSTANCES=10
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444

chrome-2:
  image: selenium/node-chrome:3.141
  links:
  - selenium-hub:hub
  volumes:
  - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
  environment:
    - NODE_MAX_SESSION=5
    - NODE_MAX_INSTANCES=10
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444

chrome-3:
  image: selenium/node-chrome:3.141
  links:
  - selenium-hub:hub
  volumes:
  - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
  environment:
    - NODE_MAX_SESSION=5
    - NODE_MAX_INSTANCES=10
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444

chrome-4:
  image: selenium/node-chrome:3.141
  links:
  - selenium-hub:hub
  volumes:
  - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
  environment:
    - NODE_MAX_SESSION=5
    - NODE_MAX_INSTANCES=10
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444